# Generated by Django 4.2.5 on 2024-02-22 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Рассчёт', 'verbose_name_plural': 'Рассчёты'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Вид рассчёта', 'verbose_name_plural': 'Виды рассчёта'},
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='name',
        ),
        migrations.AddField(
            model_name='calculation',
            name='debt',
            field=models.IntegerField(null=True, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 11, 5, 19, 297115, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(default='units/default.jpg', upload_to='units', verbose_name='Фото'),
        ),
        migrations.AlterModelTable(
            name='calculation',
            table=None,
        ),
    ]
